# Generated by Django 4.2.9 on 2024-01-19 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0006_alter_sitesetup_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetup',
            options={'verbose_name': 'Setup', 'verbose_name_plural': 'Setup'},
        ),
    ]
