# Generated by Django 4.2.9 on 2024-01-19 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0008_menulink_site_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/'),
        ),
    ]
