# Generated by Django 4.2.9 on 2024-01-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_created_by_post_updated_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
    ]
